#nullable enable
using System;
using System.Collections.Generic;

namespace SmartGridSuite.Contracts.Tickets
{
    public sealed class SubmitTicketWriteUpRequest
    {
        /*
         * Generated by the client before the first submission attempt and reused
         * for every retry of that exact confirmed write-up.
         */
        public Guid ClientSubmissionId { get; set; }

        /*
         * Site the client resolved immediately before submission.
         * The API uses this to verify that the supplied TicketId still
         * belongs to the dashboard site and never silently redirects
         * the write-up to another ticket.
         */
        public string Site { get; set; } = "";

        public string FinalWriteUpText { get; set; } = "";

        public string SiteHistoryWriteUpText { get; set; } = "";

        public string SubmittedBy { get; set; } = "";

        public List<uint> WriteUpFlagIds { get; set; } = new();

        public List<uint> ReferToOptionIds { get; set; } = new();

        /*
         * Technicians selected in the Submit Write-Up preview.
         *
         * All crew technicians will be selected by default. The submitting
         * technician may remove unavailable technicians before confirming.
         */
        public List<SubmitTicketWriteUpTechnician> SelectedTechnicians { get; set; } = new();

        public bool EquipmentWasSwapped { get; set; }

        public bool IpAddressWasChanged { get; set; }
    }

    public sealed class SubmitTicketWriteUpTechnician
    {
        public uint? TechnicianId { get; set; }

        public string EmployeeId { get; set; } = "";

        public string TechnicianName { get; set; } = "";
    }
}