#nullable enable
using System;
using System.Collections.Generic;

namespace SmartGridSuite.Contracts.Tickets
{
    public sealed class SubmitTicketWriteUpRequest
    {
        /*
         * Generated by the client before the first submission attempt and reused
         * for every retry of that exact confirmed write-up.
         */
        public Guid ClientSubmissionId { get; set; }

        public string FinalWriteUpText { get; set; } = "";

        public string SiteHistoryWriteUpText { get; set; } = "";

        public string SubmittedBy { get; set; } = "";

        public List<uint> WriteUpFlagIds { get; set; } = new();

        public List<uint> ReferToOptionIds { get; set; } = new();

        public bool EquipmentWasSwapped { get; set; }

        public bool IpAddressWasChanged { get; set; }
    }
}